name: Unit Tests
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go: ["1.26", "1.27"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{matrix.go}}
          check-latest: true

      - name: Lint and Test
        uses: choria-io/actions/lint_and_test/go@64294f0e09350d15dcb974c464c11e169622057a # v0.0.1
        with:
          ginkgo: "v2"
